sudo: false

env:
  global:
    - ANDROID_API_LEVEL=28
    - ANDROID_EMULATOR_LEVEL=23
    - ANDROID_BUILD_TOOLS_VERSION=28.0.0
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=20

language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - android-$ANDROID_EMULATOR_LEVEL
    - sys-img-armeabi-v7a-google_apis-$ANDROID_EMULATOR_LEVEL


    # The BuildTools version used by your project
    - build-tools-28.0.0

    # The SDK version used to compile your project
    - android-28

  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
  before_install:
    - yes | sdkmanager "platforms;android-27"
    - yes | sdkmanager "platforms;android-28"


before_install:
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager "platforms;android-26"

licenses:
  - '.+'
